.version:6
CHANGELOG:20282
docs/UH60M-OpsManual.pdf:8268296
objects/cockpit1.obj:10011873
objects/exterior.obj:3581002
objects/gears_fh.obj:2877768
objects/particles/UH60M_particles.pss:54652
plugins/UH60M/64/libcrypto-3-x64.dll:6879232
plugins/UH60M/64/libssl-3-x64.dll:1346560
plugins/UH60M/64/lin.xpl:16673400
plugins/UH60M/64/mac.xpl:29190128
plugins/UH60M/64/win.xpl:5990400
plugins/UH60M/EndUserLicense:992
plugins/UH60M/changelog.txt:52930
plugins/UH60M/data/acturl.dat:9
plugins/UH60M/data/components/Roboto-Regular-LICENSE.txt:11358
plugins/UH60M/data/components/Roboto-Regular.ttf:171676
plugins/UH60M/data/components/defdecore.png:987
plugins/UH60M/data/components/interactive.png:250
plugins/UH60M/data/components/interactive.secured:544
plugins/UH60M/data/components/mouseFocusedZone.secured:544
plugins/UH60M/data/components/popupCloseButton.secured:864
plugins/UH60M/data/components/popupResizeButton.secured:576
plugins/UH60M/data/components/readme.txt:46
plugins/UH60M/data/components/rectangle.secured:544
plugins/UH60M/data/init/initAvionics.secured:5104
plugins/UH60M/data/init/initBasicHelpers.secured:544
plugins/UH60M/data/init/initContextWindows.secured:9280
plugins/UH60M/data/init/initDefaultEventHandlers.secured:1568
plugins/UH60M/data/init/initFilesystemHelpers.secured:1296
plugins/UH60M/data/init/initMain.secured:19072
plugins/UH60M/data/init/initMathHelpers.secured:1408
plugins/UH60M/data/init/initProcessing.secured:3904
plugins/UH60M/data/init/initProperties.secured:14816
plugins/UH60M/data/init/initResourcesLoaders.secured:2784
plugins/UH60M/data/init/initSubpanelCreator.secured:3520
plugins/UH60M/data/init/initTableHelpers.secured:1504
plugins/UH60M/data/init/readme.txt:47
plugins/UH60M/data/modules/3rd-modules/aircraft_configs/uh60m_config.lua:1963
plugins/UH60M/data/modules/3rd-modules/json_lib.lua:9652
plugins/UH60M/data/modules/Custom Module/CDU1.secured:111888
plugins/UH60M/data/modules/Custom Module/CDU2.secured:111888
plugins/UH60M/data/modules/Custom Module/FDCP.secured:28880
plugins/UH60M/data/modules/Custom Module/MFD.secured:163216
plugins/UH60M/data/modules/Custom Module/airfuel.secured:10112
plugins/UH60M/data/modules/Custom Module/anims.secured:27008
plugins/UH60M/data/modules/Custom Module/configs.secured:20400
plugins/UH60M/data/modules/Custom Module/controls.secured:25824
plugins/UH60M/data/modules/Custom Module/dtc_config_sender.secured:2400
plugins/UH60M/data/modules/Custom Module/dtc_receiver.secured:3728
plugins/UH60M/data/modules/Custom Module/engines.secured:15344
plugins/UH60M/data/modules/Custom Module/events.secured:19248
plugins/UH60M/data/modules/Custom Module/failures.secured:2784
plugins/UH60M/data/modules/Custom Module/formation.secured:3392
plugins/UH60M/data/modules/Custom Module/icam.secured:13808
plugins/UH60M/data/modules/Custom Module/images/uh60-side.png:3299
plugins/UH60M/data/modules/Custom Module/limits.secured:992
plugins/UH60M/data/modules/Custom Module/menu.secured:22592
plugins/UH60M/data/modules/Custom Module/message.secured:4848
plugins/UH60M/data/modules/Custom Module/mission.secured:37216
plugins/UH60M/data/modules/Custom Module/nav.secured:23088
plugins/UH60M/data/modules/Custom Module/ops.secured:34688
plugins/UH60M/data/modules/Custom Module/patch.secured:6768
plugins/UH60M/data/modules/Custom Module/perf.secured:2720
plugins/UH60M/data/modules/Custom Module/rotors.secured:6352
plugins/UH60M/data/modules/Custom Module/slingops.secured:8720
plugins/UH60M/data/modules/Custom Module/sys.secured:40672
plugins/UH60M/data/modules/Custom Module/vibration.secured:1936
plugins/UH60M/data/modules/Custom Module/winch.secured:4992
plugins/UH60M/data/modules/main.secured:99456
plugins/UH60M/data/modules/state.txt:79
plugins/UH60M/data/output/SASLLog.txt:2843
plugins/UH60M/liblinux/libc++.so:28
plugins/UH60M/liblinux/libc++.so.1:787328
plugins/UH60M/liblinux/libc++.so.1.0:787328
plugins/UH60M/liblinux/libc++abi.so:194968
plugins/UH60M/liblinux/libc++abi.so.1:194968
plugins/UH60M/liblinux/libc++abi.so.1.0:194968
plugins/UH60M/version.txt:182
uh60m.acf:730291
uh60m_prefs.txt:383
